In [43]:
# «Машинное обучение и анализ данных» на Coursera
import numpy as np
x = np.random.normal(loc=15, scale=10, size=(3, 2))
print('x\n', x, end='\n\n')

x_mean = np.mean(x, axis=0)
print('x_mean\n', x_mean, end='\n\n')
x_std = np.std(x, axis=0)
print('x_std\n', x_std, end='\n\n')


result = (x - x_mean) / x_std
print('result\n' ,result)

x
 [[15.84528088 20.54896853]
 [14.29923759 20.18911223]
 [14.78269094 13.1441728 ]]

x_mean
 [14.97573647 17.96075119]

x_std
 [0.64576177 3.40900226]

result
 [[ 1.34654055  0.75923016]
 [-1.04759822  0.65366957]
 [-0.29894233 -1.41289973]]


In [45]:
z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [48]:
z_sum_over_10 = np.sum(z, axis=1)
print('z_sum_over_10\n', z_sum_over_10)
np.nonzero(z_sum_over_10 > 10)

z_sum_over_10
 [ 9 13  7  9 27 12]


(array([1, 4, 5]),)

In [54]:
a = np.eye(3,3)
print(a)
b = np.eye(6,3)
print('\n',b)
np.vstack((a, b))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])